# Generated by Django 5.1.7 on 2025-04-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0004_alter_booking_check_in_alter_booking_check_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
