# Generated by Django 5.1.7 on 2025-04-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0006_hotel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.CharField(default='somewhere', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
