# Generated by Django 5.1.7 on 2025-04-15 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0008_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='holidays.user'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='query',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='holidays.query'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='holidays.user'),
        ),
        migrations.AlterField(
            model_name='webadmin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='holidays.user'),
        ),
    ]
